spring.application.name=OneClickServiceBackend

# CONEXION A MYSQL
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

server.port=8080
server.address=0.0.0.0

spring.datasource.hikari.max-lifetime=30000
spring.datasource.hikari.keepalive-time=10000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.validation-timeout=5000